providers = ["node"]

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096"
PORT = "9000"

[phases.setup]
nixPkgs = ["...", "git"]
cmds = [
  "git init"
]

[phases.install]
# Yarn 3 in this repo runs in node_modules mode and no lockfile is checked into git,
# so use npm to install all dependencies required for the build.
cmds = [
  "npm install --include=dev"
]

[phases.build]
cmds = [
  "npm run build:prod",
  "npm prune --omit=dev",
  "rm -rf .git"
]

[start]
cmd = "npm run serve"

